version: '3.4'

services:
  web:
    image: gerfficient-web
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - FLASK_DATA=/data
      - FLASK_SECRET=DEBUG_SECRET
    ports:
      - 5001:5000
